[2025-01-15T13:10:38.935+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T13:10:24.302035+00:00 [queued]>
[2025-01-15T13:10:38.940+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T13:10:24.302035+00:00 [queued]>
[2025-01-15T13:10:38.940+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T13:10:38.940+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-15T13:10:38.941+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T13:10:38.947+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_load> on 2025-01-15 13:10:24.302035+00:00
[2025-01-15T13:10:38.949+0000] {standard_task_runner.py:52} INFO - Started process 2213 to run task
[2025-01-15T13:10:38.950+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_load', 'manual__2025-01-15T13:10:24.302035+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmp0ecnyf9k', '--error-file', '/tmp/tmpr4x4li5o']
[2025-01-15T13:10:38.951+0000] {standard_task_runner.py:80} INFO - Job 13: Subtask data_load
[2025-01-15T13:10:38.981+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T13:10:24.302035+00:00 [running]> on host 85e61d7672fe
[2025-01-15T13:10:39.015+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_load
AIRFLOW_CTX_EXECUTION_DATE=2025-01-15T13:10:24.302035+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-15T13:10:24.302035+00:00
[2025-01-15T13:10:39.015+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-15T13:10:39.016+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/dags/load.py']
[2025-01-15T13:10:39.020+0000] {subprocess.py:85} INFO - Output:
[2025-01-15T13:10:47.690+0000] {subprocess.py:96} INFO - Command exited with return code 0
[2025-01-15T13:10:47.748+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=ETL_influencer_marchendise, task_id=data_load, execution_date=20250115T131024, start_date=20250115T131038, end_date=20250115T131047
[2025-01-15T13:10:47.799+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-01-15T13:10:47.828+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
